version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: crud_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    links:
      - app


  #PHP Service
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: root
    image: php:8.2-fpm
    container_name: crud_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db

  #MySQL Service
  db:
    image: mysql:8
    container_name: crud_mysql
    restart: always
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: crud
      MYSQL_DATABASE: crud
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

#Volumes
volumes:
  dbdata:
    driver: local
