version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/dev.Dockerfile
    container_name: crud_backend
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/backend/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: crud_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: crud_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
