version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/prod.Dockerfile
    container_name: crud_backend_prod
    restart: unless-stopped
    volumes:
      - ./docker/backend/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: crud_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: crud_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
